spring:

# 线下数据库配置
#  datasource:
#    username: "root"
#    password: "adminmysql"
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/xiang_shan?characterEncoding=utf-8&useSSL=false

#线上数据库配置
  datasource:
   username: "root"
   password: "uAiqwVwjJ8-i"
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://39.108.222.55:3306/xiang_shan?characterEncoding=utf-8&useSSL=false

  session:
    store-type: none

  redis:
    password: adminredis

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb

travischenn:

  #认证控制
  security:

    #浏览器配置
    browser:
      login-page-url: /page/admin/login.html
      auth-redirect-type: json
      remember-me-second: 3600

  file:
    alibaba:
      access-key-id: LTAIDZlwxaMAEJFk
      access-key-secret: WILuvfV8x9dGC4XnBU7HCpQqbXMUpc
      end-point: http://oss-cn-shenzhen.aliyuncs.com
      bucket-name: xiang-shan-quality-platform
      access-url: http://xiang-shan-quality-platform.oss-cn-shenzhen.aliyuncs.com

server:
  port: 80

logging:
  path: /opt/log/tomcat
  file: /opt/log/tomcat/springboot-starter.log
